// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("clickhouselogsexporter")
	ScopeName = "github.com/bylonis/bylonis-otel-collector/exporter/clickhouselogsexporter"
)

const (
	LogsStability = component.StabilityLevelStable
)
